default_install_hook_types: [pre-commit, commit-msg]
default_stages: [commit, manual]

# Use the backend virtual environment
default_language_version:
    python: python3.9

repos:
# Python checks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
    - id: black
      files: ^backend/
      language_version: python3.9

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      files: ^backend/

- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      files: ^backend/
      additional_dependencies: [flake8-docstrings]

# Frontend checks
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.1.0
  hooks:
    - id: prettier
      types_or: [javascript, jsx, ts, tsx, css, json]
      files: ^frontend/
      additional_dependencies:
        - prettier@3.1.0

- repo: local
  hooks:
    - id: eslint
      name: eslint
      entry: bash -c 'cd frontend && npm run lint'
      language: system
      types_or: [javascript, jsx, ts, tsx]
      files: ^frontend/
      pass_filenames: false 