version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///app.db
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "pip install flake8 black isort &&
             flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics &&
             black --check . &&
             isort --check-only --diff . &&
             pytest -v"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CI=true
    depends_on:
      - backend 