name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build and test backend
        run: |
          docker build -t backend-tests ./backend
          docker run --rm backend-tests sh -c "pip install flake8 black isort && flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics && black --check . && isort --check-only --diff . && pytest -v"
      
      - name: Build and test frontend
        run: |
          docker build -t frontend-tests ./frontend
          docker run --rm -e CI=true frontend-tests
