name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build and test backend
        run: |
          docker build -t backend-tests ./backend
          mkdir -p test-results
          docker run --rm -v ${PWD}/test-results:/test-results backend-tests sh -c "pytest -v --junitxml=/test-results/pytest.xml"

      - name: Publish Backend Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Front End Test Results
          path: test-results/jest.xml

      - name: Backend Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Backend Test Results
          path: test-results/pytest.xml
          reporter: java-junit

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build and test frontend
        run: |
          docker build -t frontend-tests ./frontend
          mkdir -p test-results
          docker run --rm \
            -v ${PWD}/test-results:/test-results \
            -e JEST_JUNIT_OUTPUT_DIR=/test-results \
            -e JEST_JUNIT_OUTPUT_NAME=jest.xml \
            frontend-tests sh -c " \
              npm rebuild canvas --update-binary && \
              CI=true npm test -- --watchAll=false --reporters=jest-junit"  

      - name: Publish Frontend Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Front End Test Results
          path: test-results/jest.xml

      - name: Frontend Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Frontend Test Results
          path: test-results/jest.xml
          reporter: java-junit



